name: Manual Changeset Version

on:
  workflow_dispatch:

jobs:
  changeset-version:
    name: Create changeset PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      checks: write
      deployments: write
      discussions: write
      id-token: write
      issues: write
      packages: write
      pages: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Create Release PR
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
