name: Run Tests on PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright
        run: npx playwright install

      - name: Install Playwright deps
        run: npx playwright install-deps

      - name: Run tests
        run: yarn test
