name: Publish Fiber Core Web
permissions: write-all
on:
  workflow_dispatch:

jobs:
  update-package-version:
    name: Update package version in fiber web
    runs-on: ubuntu-latest
    steps:
      - name: Set Git User
        run: git config --global user.email "fady.mehany@btech.com" && git config --global user.name "fadykhayratblb"

      - name: Checkout fiber-web repository
        uses: actions/checkout@v3
        with:
          repository: fadykhayratblb/new-figma-token
          ref: main
          path: new-figma-token

      - name: Update package version
        run: |
          cd new-figma-token
          git checkout -b update-package-version
          sed -i 's/"@rollup\/plugin-dynamic-import-vars"/"@btechlabs\/fiber-core-web@3"/g' package.json
          git add package.json
          git commit -am "chore: bump package version"
          git push origin update-package-version

  open-pull-request:
    name: Open pull request in fiber web
    runs-on: ubuntu-latest
    needs: update-package-version
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump Fiber Web Core version"
          branch: update-package-version
          title: "Update web core package version in package json"
          body: "Automated pull request after releasing new version."
          labels: "automated"
          base: main
          head: fadykhayratblb:update-package-version
          base-repo: fadykhayratblb/new-figma-token
